/**
 * Enriched property types for local LLM-generated metadata.
 *
 * These types extend the base Property with SEO, marketing, and
 * classification fields that can be generated by a local LLM worker
 * (e.g. Gemma 4 E4B via Ollama) at zero API cost.
 */

/** Normalized property category derived by the local LLM */
export type PropertyCategory =
  | "villa"
  | "apartment"
  | "penthouse"
  | "chalet"
  | "mansion"
  | "townhouse"
  | "estate"
  | "loft";

/** Luxury tier classification */
export type LuxuryTier = "ultra-luxury" | "luxury" | "premium";

/** Enrichment metadata generated by local LLM worker */
export interface PropertyEnrichment {
  /** Property ID matching the source listing */
  id: string;

  /** Extracted country name */
  country: string;

  /** Normalized currency code (ISO 4217) */
  currency: string;

  /** Numeric price value (no currency/symbols) */
  priceNumeric: number;

  /** Price per sqft, calculated */
  pricePerSqft: number;

  /** Normalized property category */
  propertyCategory: PropertyCategory;

  /** Luxury tier classification */
  luxuryTier: LuxuryTier;

  /** Top 5 short feature tags extracted from description + amenities */
  keyFeatures: string[];

  /** SEO meta title (max 60 chars) */
  seoMetaTitle: string;

  /** SEO meta description (max 160 chars) */
  seoMetaDescription: string;

  /** Marketing tagline (max 10 words) */
  tagline: string;

  /** URL-friendly slug */
  slug: string;

  /** Social media bullet points (max 3, each max 25 words) */
  socialBullets: string[];
}
